$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd =  # We removed the quickshell focus command here
    inhibit_sleep = 3
}
# ---------------------------

listener {
    timeout = 300 # 5mins
    on-timeout = loginctl lock-session
}

# Keep this part if you want the screen to turn off after 20 mins
listener {
    timeout = 1200 # 20mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Uncomment this if you want it to auto-sleep after 30 mins
# listener {
#     timeout = 1800 
#     on-timeout = $suspend_cmd
# }
