# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule = workspace 1, class:^(code)$
windowrule = workspace 4, class:^(chrome-fmgjjmmmlfnkbppncabfkddbjimcfncm-Default)$, title:^(Gmail)(.*)$
windowrule = workspace 4, class:^(Spotify)$


windowrulev2 = opacity 0.88 override 0.88 override, class:.*
